FROM spark-base

# Set default environment variables. These can also be set at the command line when invoking /bin/spark-submit
ENV MASTER_CONTAINER_NAME=spark-master
ENV SPARK_EXECUTOR_MEMORY=1G
ENV SPARK_EXECUTOR_CORES=1

# Install libraries
COPY ./resources/requirements.txt .
RUN pip install -r requirements.txt

# Copy properties files into container
COPY ./resources/log4j.properties ./resources/spark-defaults.conf $SPARK_HOME/conf/

EXPOSE 4040 8888

WORKDIR /home/

RUN pip install pymongo notebook

CMD jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=